version: "3.8"

services:
  mariner:
    image: ghcr.io/sasue/mariner:latest
    container_name: mariner
    restart: unless-stopped
    init: true

    command: ["waitress-serve", "--listen=0.0.0.0:5000", "mariner.server.app:app"]

    ports:
      - "5000:5000"

    devices:
      - "/dev/serial0:/dev/ttyS0"
      
    group_add:
      - dialout
    
    volumes:
      - /mnt/usb:/mnt/usb_share

    networks:
      - proxy-net

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  proxy-net:
    external: true
